import { describe, it, expect } from 'vitest';
import { stalePlanError } from '../src/lib/meeting-plan-publish';

/**
 * Meeting plan published under the wrong date (reported 2026-08-08).
 *
 * Symptom: "I put the date in as August 16th, but it reverted to August 9th.
 * I added another meeting for August 23rd and it also reverted."
 *
 * Not a date-parsing or timezone fault, and not a "next available slot" rule —
 * Publish used the plan generated by the LAST click of Generate. Changing the
 * date field left that plan in state with Publish still enabled, so it wrote
 * the old plan under the old date while the field on screen showed the new
 * one. Aug 9 was simply the default (next Sunday from Aug 8), which is why it
 * looked like the date kept snapping back to the next meeting.
 *
 * Reproduced and re-verified in a browser; these pin the rule both the
 * builder and the publish action now share. The action itself needs a leader
 * cookie, which this suite has no harness for (D-049).
 */
describe('Meeting plan publish date guard', () => {
  it('StalePlan_IsRefused_WhenTheDateChangedAfterGenerating', () => {
    // The exact reported case: generated for Aug 9, field moved to Aug 16.
    const err = stalePlanError('2026-08-09', '2026-08-16');
    expect(err).toBe(
      'This plan was generated for 2026-08-09, not 2026-08-16 — generate a plan for 2026-08-16 first.'
    );
  });

  it('MatchingPlan_Publishes_WhenTheDatesAgree', () => {
    expect(stalePlanError('2026-08-16', '2026-08-16')).toBeNull();
  });

  it('SecondAttempt_IsAlsoRefused_WhenMovingToAThirdDate', () => {
    // Aug 23 "also reverted" — same stale payload, a second date change.
    expect(stalePlanError('2026-08-09', '2026-08-23')).not.toBeNull();
  });

  it('NoSelectedDate_IsNotTreatedAsAMismatch', () => {
    // A caller that doesn't track a selected date has nothing to contradict;
    // the payload's own date stands rather than the guard blocking a publish
    // that was never ambiguous.
    expect(stalePlanError('2026-08-16', '')).toBeNull();
  });
});
